import os
from quart import Quart, render_template
from quart_compress import Compress


PORT =                  os.getenv('PORT')           # get the port generated by railway


app = Quart(__name__, static_url_path='/static')
app.config["SESSION_REVERSE_PROXY"] =       True    # required to get a visitors IP through railway
Compress(app)


@app.errorhandler(404)
async def handle_not_found(e):
    return '<h1>😦</h1><b>404</b> Not found.<p><a href="/">return</a>' 
 

@app.route("/")
async def index() -> str:
        return await render_template("index.html")
